### ISSUE TITLE
Kamera sie nie obraca w prawo

### ISSUE THREAD

**Issue by SpookyZeb** [unhappystaek/Five-nights-at-REDACTED-s#5]
Wgl na początku myślałem, że to wina dwóch monitorów, ale wyłączyłem drugi monitor no i dupa.

Napraw ok ok ok

best wishes

**Comment by SpookyZeb** [comment]
prosze napraw bo chce pograc a nie moge

**Comment by unhappystaek** [comment]
u mnie działa
